# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "heidi"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hartog C. de Mik"]
  s.date = "2012-03-01"
  s.description = "CI-Joe alike CI system called Heidi."
  s.email = "hartog@organisedminds.com"
  s.executables = ["heidi", "heidi_web"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/heidi",
    "bin/heidi_web",
    "heidi.gemspec",
    "lib/heidi.rb",
    "lib/heidi/build.rb",
    "lib/heidi/builder.rb",
    "lib/heidi/git.rb",
    "lib/heidi/hook.rb",
    "lib/heidi/integrator.rb",
    "lib/heidi/project.rb",
    "lib/heidi/shell.rb",
    "lib/heidi/tester.rb",
    "lib/heidi/web.rb",
    "lib/heidi/web/assets/css/bootstrap-responsive.css",
    "lib/heidi/web/assets/css/bootstrap.css",
    "lib/heidi/web/assets/css/colors.css",
    "lib/heidi/web/assets/css/docs.css",
    "lib/heidi/web/assets/images/HeidiBlue-480.png",
    "lib/heidi/web/assets/images/HeidiBlue.gif",
    "lib/heidi/web/assets/images/OrganisedMinds.png",
    "lib/heidi/web/assets/images/heidi.jpeg",
    "lib/heidi/web/assets/img/glyphicons-halflings-white.png",
    "lib/heidi/web/assets/img/glyphicons-halflings.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_009_magic.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_042_group.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_079_podium.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_082_roundabout.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_155_show_thumbnails.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_163_iphone.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_214_resize_small.png",
    "lib/heidi/web/assets/img/glyphicons/glyphicons_266_book_open.png",
    "lib/heidi/web/assets/js/README.md",
    "lib/heidi/web/assets/js/application.js",
    "lib/heidi/web/assets/js/bootstrap-alert.js",
    "lib/heidi/web/assets/js/bootstrap-button.js",
    "lib/heidi/web/assets/js/bootstrap-carousel.js",
    "lib/heidi/web/assets/js/bootstrap-collapse.js",
    "lib/heidi/web/assets/js/bootstrap-dropdown.js",
    "lib/heidi/web/assets/js/bootstrap-modal.js",
    "lib/heidi/web/assets/js/bootstrap-popover.js",
    "lib/heidi/web/assets/js/bootstrap-scrollspy.js",
    "lib/heidi/web/assets/js/bootstrap-tab.js",
    "lib/heidi/web/assets/js/bootstrap-tooltip.js",
    "lib/heidi/web/assets/js/bootstrap-transition.js",
    "lib/heidi/web/assets/js/bootstrap-typeahead.js",
    "lib/heidi/web/assets/js/google-code-prettify/prettify.css",
    "lib/heidi/web/assets/js/google-code-prettify/prettify.js",
    "lib/heidi/web/assets/js/jquery.js",
    "lib/heidi/web/views/build.erb",
    "lib/heidi/web/views/commit.erb",
    "lib/heidi/web/views/config.erb",
    "lib/heidi/web/views/home.erb",
    "lib/heidi/web/views/layout.erb",
    "lib/heidi/web/views/new_project.erb",
    "lib/heidi/web/views/project.erb",
    "lib/heidi/web/views/project_header.erb",
    "spec/heidi/build_spec.rb",
    "spec/heidi/builder_spec.rb",
    "spec/heidi/git_spec.rb",
    "spec/heidi/hook_spec.rb",
    "spec/heidi/integrator_spec.rb",
    "spec/heidi/project_spec.rb",
    "spec/heidi/shell_spec.rb",
    "spec/heidi/web_spec.rb",
    "spec/heidi_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/01_rworld.rb",
    "spec/support/mock_project.rb",
    "spec/support/survivable.rb"
  ]
  s.homepage = "http://github.com/coffeeaddict/heid"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "A naive CI system"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<simple_shell>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<simple_shell>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<simple_shell>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

