#!/bin/sh

command=$1
for_a=$2

check_heidi_root()
{
  if [ ! -e ./projects ] && [ ! -d ./projects ]
  then
    echo "You're not inside Heidi" >&2
    exit 1
  fi
}

case $command in
  new)
    mkdir -p $for_a/projects
  ;;

  project)
    check_heidi_root

    # create a logs dir
    mkdir -p projects/$for_a/logs
    cd projects/$for_a

    # make a clone
    git clone $2 cached
    cd cached
    git config heidi.name $for_a
  ;;

  drop)
    check_heidi_root

    # remove build and cache dir, expose logs directly
    rm -r projects/$for_a/build
    rm -r projects/$for_a/cached
    mv projects/$for_a/logs/* projects/$for_a/
    rm -r projects/$for_a/logs
  ;;
esac